### ISSUE TITLE
Failed to start remote control: start server failed: listen tcp: lookup localhost on 8.8.8.8:53: no such host

### ISSUE THREAD

**Issue by xd003** [rclone/rclone-webui-react#110]
I am already running rclone locally and its working pretty good.
- rclone v1.53.1
- OS: [Arch linux arm](https://github.com/termuxarch/termuxarch)
- arch: arm64
- go version: go1.15

While trying to use web ui , i am getting the following error
```
rclone rcd --rc-web-gui
```
```
2020/09/18 06:47:09 NOTICE: Web GUI exists. Update skipped.
2020/09/18 06:47:09 NOTICE: Serving Web GUI
2020/09/18 06:47:09 Failed to start remote control: start server failed: listen tcp: lookup localhost on 8.8.8.8:53: no such host
```

**Comment by ncw** [comment]
What OS are you running on?

It looks like it doesn't understand the `localhost` hostname.

What does `host localhost` or `ping localhost` do?

Normally you add `localhost` to `/etc/hosts`

```
$ cat /etc/hosts
127.0.0.1	localhost
```

**Comment by xd003** [comment]
> What OS are you running on?
> It is Arch Linux arm rootfs

> What does `host localhost` or `ping localhost` do?
> ```
❯ ping localhost
PING localhost(localhost (::1)) 56 data bytes
64 bytes from localhost (::1): icmp_seq=1 ttl=64 time=0.197 ms
64 bytes from localhost (::1): icmp_seq=2 ttl=64 time=0.364 ms
64 bytes from localhost (::1): icmp_seq=3 ttl=64 time=0.313 ms
64 bytes from localhost (::1): icmp_seq=4 ttl=64 time=0.198 ms
```

❯ cat /etc/hosts returns the following 
````
# Static table lookup for hostnames.
# See hosts(5) for details.%
```
@SDRausty i wonder if the /etc/hosts file is intended to be like this

I tried adding ```127.0.0.1        localhost``` to /etc/hosts but that didn't seem to resolve this issue

**Comment by SDRausty** [comment]
> `host localhost`
`zsh: command not found: host`

Please try `pci dnsutils`:
`[root22:05~]$ pacman -Ql dnsutils|f \/bin\/host`
`22:bind /usr/bin/host`

**Comment by xd003** [comment]
@SDRausty thanks for the input , just installing ```dnsutils``` has apparently fixed this issue

**Comment by SDRausty** [comment]
> installing dnsutils has apparently fixed this issue

Glad to read that this has resolved the issue @xd003!
