### ISSUE TITLE
error when attempting "SHARE WITH LINK" function in explorer

### ISSUE THREAD

**Issue by whitewhidow** [rclone/rclone-webui-react#112]
Hi, when viewing files trough the explorer, and clicking the "share with link" button, i get the following error:

  | t.createNewPublicLink | @ | index.js:73
-- | -- | -- | --
  | linkShareHandle | @ | FilesView.js:260
  | onClick | @ | FileActions.js:35
  | n.onClick | @ | DropdownItem.js:50
  | u | @ | react-dom.production.min.js:14
  | p | @ | react-dom.production.min.js:14
  | (anonymous) | @ | react-dom.production.min.js:14
  | y | @ | react-dom.production.min.js:15
  | at | @ | react-dom.production.min.js:52
  | ot | @ | react-dom.production.min.js:51
  | ut | @ | react-dom.production.min.js:52
  | pt | @ | react-dom.production.min.js:56
  | D | @ | react-dom.production.min.js:287
  | B | @ | react-dom.production.min.js:19
  | Jt | @ | react-dom.production.min.js:70
  | Yt | @ | react-dom.production.min.js:69
  | t.unstable_runWithPriority | @ | scheduler.production.min.js:19
  | Wo | @ | react-dom.production.min.js:122
  | M | @ | react-dom.production.min.js:287
  | Gt

**Comment by negative0** [comment]
Hi. Please share more information about what remote you are trying to use (gdrive, s3 etc), and the rclone log, You can use `-vvv` while running rclone to get the log.

**Comment by whitewhidow** [comment]
have tried with both gdrive and hotmail, cant get to the logs anymore atm sorry, when i do, ill update

**Comment by ewwink** [comment]
I also got same problem when I click "share with link"
```
Uncaught ReferenceError: tools is not defined
    at t.createNewPublicLink (index.js:73)
```

it is `tools` or `_Tools` ? 

`index.js` code

```javascript
var _Tools = require("./Tools");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

// const axiosInstance = require('./axiosInstance');
// const urls = require('./endpoint');
// const tools = require('./Tools')
....
....
....
var createNewPublicLink = exports.createNewPublicLink = function createNewPublicLink(remoteName, remotePath) {
	remoteName = tools.addColonAtLast(remoteName);
	return new Promise(function (resolve, reject) {
```

**Comment by ewwink** [comment]
temporary fix, in file `9.ef553d88.chunk.js` replace 

```
return e=tools.addColonAtLast(e)
```

with

```
return e=s.addColonAtLast(e)
```

**Comment by negative0** [comment]
Thanks for the change @ewwink,

I have made that change in the source code.
