### ISSUE TITLE
127.0.0.1 doesn't work on Firefox

### ISSUE THREAD

**Issue by yaakovfeldman** [rclone/rclone-webui-react#117]
I am very pleased with the rclone gui but I have one issue.

My default browser is Firefox 83 on Windows 10. When I run a command starting `rclone --rc --rc-web-gui` (and supplying a username and password) and the browser opens automatically, it opens as an address starting `http://127.0.0.1:5572/?login_token=`...

I can log in to this through http auth and the GUI loads correctly, but it shows as disconnected in the top right corner and the overview section says `Status: Cannot connect to rclone backend. There is a problem with connecting to {ipAddress}.`

If I change `127.0.0.1` to `localhost` in the url bar then it loads correctly and I can see my job.

In Chrome, it works with either address.

I tried to mitigate this by making the auto-open page use `localhost` but even if I explicitly set `--rc-addr=localhost:5572` it still opens as `127.0.0.1`. This means I have to manually change the address in Firefox each time it opens.

This may just be a Firefox issue, but even so, is there any way to mitigate it by controlling the url opened?

**Comment by ncw** [comment]
I think what is happening is that rclone is resolving "localhost" (which is the default) into 127.0.0.1

This is the actual bit of code responsible

https://github.com/rclone/rclone/blob/e45716cac2ab3405a41d15e394337affce50ad0b/cmd/serve/httplib/httplib.go#L382-L386

If you comment it out then it won't translate `localhost` to `127.0.0.1`

Its main purpose is when you put in `--rc-addr :8080` it translates the address to something sensible or when you use `localhost:0` to auto assign a port it reads the port back as something sensible.

I'm pretty sure that `localhost` will always resolve correctly in browsers, but I'm not 100% sure about that.

So I could put in a work-around to return the original address provided it didn't start with ":" and didn't end with ":0"

I had a go with this - try this rclone beta

[v1.54.0-beta.4971.ea64794d2.fix-localhost](https://beta.rclone.org/branch/fix-localhost/v1.54.0-beta.4971.ea64794d2.fix-localhost/) on branch [fix-localhost](https://github.com/rclone/rclone/tree/fix-localhost) (uploaded in 15-30 mins)

**Comment by yaakovfeldman** [comment]
Works perfectly thank you. The link didn't include a Windows build but it was easy to compile the branch myself.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in rclone v1.54

Thanks for testing :-)
