### ISSUE TITLE
Config: Can't enter hostname in FTP config

### ISSUE THREAD

**Issue by ncw** [rclone/rclone-webui-react#12]
Clicking doesn't select example.com from the dropdown menu.

I can't click in the box and type stuff.

Users need to be able to type in their own values for all config items - the examples are just that, examples.

![image](https://user-images.githubusercontent.com/536803/59192490-85e29200-8b7a-11e9-9564-9a9122099fcf.png)

**Comment by negative0** [comment]
In some cases, the examples are valid values which the input can take. For example this:
```
"Examples": [
                    {
                        "Value": "off",
                        "Help": "Don't encrypt the file names.  Adds a \".bin\" extension only.",
                        "Provider": ""
                    },
                    {
                        "Value": "standard",
                        "Help": "Encrypt the filenames see the docs for the details.",
                        "Provider": ""
                    },
                    {
                        "Value": "obfuscate",
                        "Help": "Very simple filename obfuscation.",
                        "Provider": ""
                    }
                ],
```
OR
```
"Examples": [
                    {
                        "Value": "true",
                        "Help": "Encrypt directory names.",
                        "Provider": ""
                    },
                    {
                        "Value": "false",
                        "Help": "Don't encrypt directory names, leave them intact.",
                        "Provider": ""
                    }
                ],
```

How can we restrict in some cases and relax in others? Having these restrictions help us enforce rules to avoid any config errors.

**Comment by negative0** [comment]
In some cases, the examples are valid values which the input can take. For example this:

```
"Examples": [
                    {
                        "Value": "off",
                        "Help": "Don't encrypt the file names.  Adds a \".bin\" extension only.",
                        "Provider": ""
                    },
                    {
                        "Value": "standard",
                        "Help": "Encrypt the filenames see the docs for the details.",
                        "Provider": ""
                    },
                    {
                        "Value": "obfuscate",
                        "Help": "Very simple filename obfuscation.",
                        "Provider": ""
                    }
                ],
```
OR
```
"Examples": [
                    {
                        "Value": "true",
                        "Help": "Encrypt directory names.",
                        "Provider": ""
                    },
                    {
                        "Value": "false",
                        "Help": "Don't encrypt directory names, leave them intact.",
                        "Provider": ""
                    }
                ],
```
How can we restrict in some cases and relax in others? Having these restrictions help us enforce rules to avoid any config errors.

**Comment by ncw** [comment]
> In some cases, the examples are valid values which the input can take. For example this:

I would say in all cases the examples are valid values which the input can take.  However they aren't all the valid values.  `rclone config` does this by allowing you to type `1`, `2`,... to select the example **or** type in your own value.

For certain types of input it doesn't make sense to type in your own value (eg Boolean) but anything "string"-y you want the user to be able to type their own value in as well being able to select from the examples.

So I'm imagining an input box which you can type into, plus a dropdown which fills in the input box for you. 

How does that sound?

**Comment by negative0** [comment]
For now, I have added an input field instead of a select. I will get back to this issue next week.

**Comment by ncw** [comment]
> For now, I have added an input field instead of a select. I will get back to this issue next week.

Great :-)
