### ISSUE TITLE
Changing bandwith limit format check in gui

### ISSUE THREAD

**Issue by LeendertPlas** [rclone/rclone-webui-react#120]
in the beta release [1837](https://github.com/rclone/rclone/issues/1873) and in the future, there will be a bandwith limit for uploading and a separate one for downloading. Therefore the Bandwith limiter check should be changed to accept this X:Z format. While the current max speed is displayed correctly from the config, that same value would not be accepted with the current format checking system

**Comment by negative0** [comment]
@LeendertPlas Thank you for reporting this. Pushed on the master, the bwlimit should now accept the new format.
