### ISSUE TITLE
Config not visible

### ISSUE THREAD

**Issue by delegreg** [rclone/rclone-webui-react#122]
Hello team, 

I have three configs : 

1. gdrive
2. local
3. another gdrive

In the "configs" component, i see all three in the correct order.

![Capture](https://user-images.githubusercontent.com/10157065/108491143-d3962400-72a3-11eb-952b-0ce505bd85c3.PNG)

In the explorer, when i open a new component, in the dropdown only two are listed.

![Capture2](https://user-images.githubusercontent.com/10157065/108491161-d7c24180-72a3-11eb-809b-66af32a4d3ad.PNG)

Opening the third by typing its name works, but it is counter-intuitive.

**Comment by negative0** [comment]
Hi @delegreg, Thank you for reporting this bug, I have fixed it in the master branch. Will release soon.
