### ISSUE TITLE
Wordwrap causes flickering

### ISSUE THREAD

**Issue by delegreg** [rclone/rclone-webui-react#123]
In the explorer, **in "list" view mode**, when i have files that have long names (need word-wrapping), scrolling the file list causes flickering, making scrolling hard to handle. **Works fine in card view mode.**

This is especially annoying when using side-by-side (either 2 or 3) layouts.

My guess is that it's probably due to height calculations in the scrolling component, so my suggestion would be to use ellipsis rather than word-wrapping, and use some kind of tooltip to show the full name of the file.

Tested on chrome both on PC and Android, same behaviour.

**Comment by negative0** [comment]
Thanks, @delegreg for reporting this issue. There was a code that rendered an empty div till it is not visible on the viewport, which was causing that issue. Pushed on the master, Please have a look.
