### ISSUE TITLE
cannot compile under archlinux

### ISSUE THREAD

**Issue by connected201** [rclone/rclone-webui-react#137]
Hi, i tried to compile on my raspberry 4
`OS: Arch linux`

```
gcc
Python 2.7.18
```

![image](https://user-images.githubusercontent.com/20506433/127219565-85ba0e3b-8a25-4a6b-aba8-35a084c4a88f.png)
full install log:
[2021-07-27T19_46_10_750Z-debug.log](https://github.com/rclone/rclone-webui-react/files/6888396/2021-07-27T19_46_10_750Z-debug.log)
any idea how to fix it?

**Comment by connected201** [comment]
i want to read about `Getting Started` but domain [chaitanya.codes](chaitanya.codes) not unavailable anymore.
but i fixed mi issues

**Comment by negative0** [comment]
How did you solve this issue? It might be helpful to others as well, and thanks for noting the invalid link, I have removed it now.

**Comment by ghost** [comment]
hi, i don't resolved, i thinked that rclone comes without GUI,  and i wanted to compile it to use, but i was wrong, i able to install and run rclone web gui with:
`rclone rcd --rc-web-gui --rc-web-gui-no-open-browser --rc-no-auth --use-json-log --rc-user=admin --rc-pass=admin --rc-addr=0.0.0.0:8080`
(this is my example to run rclone)
