### ISSUE TITLE
Disable authentication?

### ISSUE THREAD

**Issue by Makeshift** [rclone/rclone-webui-react#139]
Is there a way to disable authentication for the web UI? It seems a little buggy (I'll open another issue for it when I've figured out some exact recreation steps), but authentication isn't required in my setup anyway.

**Comment by spali** [comment]
I have the same request.
Can't say exactly when, but sometimes I get asked once via browsers Auth dialog and still get redirected to the web based login. Sometimes it works with only the browser based dialog.

But back to the this issue ;)
I would also appreciate the possibility to disable auth.
I have it exposed behind a authenticated reverse proxy in my internal network. So disabling completely or using a specified header "Remote-User" in my case would be great.

**Comment by negative0** [comment]
Did you try using `--rc-no-auth`?

Something like 
```
rclone rcd --rc-no-auth --rc-web-gui
```

Update:

Even if you use `--rc-no-auth` right now rclone creates a random password, this should be fixed by PR attached to this issue.

**Comment by negative0** [comment]
This should be fixed on the master of rclone as well as in the next release
