### ISSUE TITLE
Cancel an existing transfer

### ISSUE THREAD

**Issue by CraftyClown** [rclone/rclone-webui-react#35]
Would it be possible to cancel an existing transfer from within the WebGUI? I started a large transfer yesterday and then changed my mind but realised I had no way of stopping it.

**Comment by negative0** [comment]
Yes. It would be possible. I have added it to my to-do list :)

**Comment by eihns** [comment]
What i even more wo nde ris, where does it download to? Ive just clicked download to see whats happening, the GUI shows the download... but there is no download starting in my webbrowser... so where does it download to...???
