### ISSUE TITLE
Where are Credentials Stored?

### ISSUE THREAD

**Issue by faxotherapy** [rclone/rclone-webui-react#39]
Hello,
I'm curious. I'd like to know where are login and password stored on MacOS? I visited folder `~/.config/rclone`, but it's not there. I wonder where it is then…

Also, how can I no longer input login nor password; I just want to have free access.

Thanks for your gracious help.

**Comment by negative0** [comment]
Hey, if you don't provide a username and password while running the gui, the default username is "gui" and the password is randomly generated each time. 

You can see the password with the ```-vv``` (debug logging) mode. 

Also, you could provide your own username and password using the --rc-user and --rc-pass parameters to the command line.
