### ISSUE TITLE
Feature Request - Parameter: --rc-port=N, changing the listening port from default 5572.

### ISSUE THREAD

**Issue by cbussa** [rclone/rclone-webui-react#55]
The default web port is of course 5572.  It'd really be nice if there were a CLI parameter (--rc-port) matching --rc-user and --rc-pass to optionally change this.

I'm on a shared box and someone else already has "absconded" with 5572, leaving me without it.  

Without looking at the source -- seemingly it's hardcoded as a literal string:
```
xd rclone | grep -i :5572
127e650 63 61 6c 68 6f 73 74 3a 35 35 37 32 6c 6f 63 61  >calhost:5572loca<
128bf60 2f 2f 6c 6f 63 61 6c 68 6f 73 74 3a 35 35 37 32  >//localhost:5572<
```
with "grep -b -o -i -a :5572 rclone" having an identical count of 2, so I lucked out on matches above.

```
$ rclone --version
rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.4

```

**Comment by cbussa** [comment]
Never mind: parameter --rc-addr **ALSO** supports specifying the port along with the IP address.  

It'd sure be nice if it were documented! ;-)

**Comment by Yexiaoxing** [comment]
It is documented https://rclone.org/flags/ and https://rclone.org/commands/rclone_rc/

`--rc-addr string IPaddress:Port or :Port to bind server to. (default "localhost:5572")`

though I think the doc in `rclone rc` is not that clear...

**Comment by negative0** [comment]
Closing this
