### ISSUE TITLE
GSoC'20

### ISSUE THREAD

**Issue by ridhishjain** [rclone/rclone-webui-react#58]
Hello, I am Ridhish Jain, Web Developer, UG at IIT Dhanbad.
I found this project interesting and it was also a part of GSoC'19.
I wanted to ask if this project can still be a part of GSoC'20??
If yes, I would love to contribute to it
If not, Is there any other way I can contribute to the organization as a web developer?

**Comment by negative0** [comment]
Yes, we are planning to put this project for GSoC '20 through CCExtractor. We will have a list of ideas soon.

**Comment by ridhishjain** [comment]
@negative0 any updates?

**Comment by negative0** [comment]
One of the problem statement is now up. https://ccextractor.org/public:gsoc:rcloneweb2

**Comment by ridhishjain** [comment]
@negative0 is there any chat channel for CCExtractor?

**Comment by negative0** [comment]
There is #rclone-ui channel

**Comment by ridhishjain** [comment]
@negative0 is this the right repo for contribution related to the problem statement you have provided? I don't see any recent activity on the repo

**Comment by negative0** [comment]
@ridhishjain this is the right repository

**Comment by negative0** [comment]
Closing this
