### ISSUE TITLE
green keeper not working properly

### ISSUE THREAD

**Issue by ridhishjain** [rclone/rclone-webui-react#70]
This should have been automatically done by green keeper. Could you check why green keeper is not updating the dependencies?

discussed more in #62
_Originally posted by @negative0 in https://github.com/rclone/rclone-webui-react/pull/62#issuecomment-586551269_

**Comment by negative0** [comment]
Depends on #71

**Comment by negative0** [comment]
The greenkeeper.io website now mentions that they will stop their operation as an independent organization from June 3rd, they have provided an alternative snyk.io. What do you think @ridhishjain @ncw

**Comment by ridhishjain** [comment]
@negative0 
why closed?? 
I think migration to sync.io is the best option (only option :sweat_smile: )
I tried migrating it in my fork https://github.com/ridhishjain/rclone-webui-react/pull/1

What do you suggest @ncw ?
