### ISSUE TITLE
Create config: 500 on emoji chars - friendly notice needed

### ISSUE THREAD

**Issue by Yexiaoxing** [rclone/rclone-webui-react#83]
When I am trying to create config using webui, and I enter "👌" it gives 500. That's expected, but in console it shows ```ERROR : rc: "config/create": error: config name contains invalid characters - may only contain 0-9, A-Z ,a-z ,_ , - and space``` which should be shown on webui.

**Comment by negative0** [comment]
Thank you @Yexiaoxing for spotting that out.

**Comment by Yexiaoxing** [comment]
Closing.
