### ISSUE TITLE
GUI doesn't search for substrings

### ISSUE THREAD

**Issue by dandv** [rclone/rclone-webui-react#96]
#### What is the problem you are having with rclone?
I'm running the GUI from the latest Beta, and the Search box, works, but only for strings that are prefixes of files or directories. For example, "oo" won't match "foo".

#### What is your rclone version (output from `rclone version`)
```
rclone v1.51.0-361-g9db8ecbc-beta
- os/arch: linux/amd64
- go version: go1.14.3
```

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive + crypt

Moved from https://github.com/rclone/rclone/issues/4270

**Comment by negative0** [comment]
Thank you for bringing that up. I will add it.

**Comment by negative0** [comment]
Done :)
