### ISSUE TITLE
Speed and AvgSpeed seem to be swapped in Running Jobs Card

### ISSUE THREAD

**Issue by JoshuaDietz** [rclone/rclone-webui-react#99]
How to reproduce:
Start an upload of a bigger file without speed limit. The "Running Jobs" card on the dashboard shows the speed and the average speed.
After some time limit the upload bandwidth.
Now the speed SHOULD drop immediately and the avg speed should over time come nearer to the the actual speed but never reach it (since the faster speed from the beginning is still included in the average).
What happens instead is that the average speed drops immediately and the speed follows.

I looked at the code for a minute and could not find a bug immediately.
Also in the Global Stats card the average speed seems to be almost the same as the speed in the Running Jobs card.

Regards
Joshua

**Comment by JoshuaDietz** [comment]
I took a closer look and it seems like this is the servers fault. The server response may look like this (markers added):
`{
	"bytes": 256567905,
	"checks": 0,
	"deletes": 0,
	"elapsedTime": 1915.595534148,
	"errors": 1,
	"fatalError": false,
	"lastError": "HTTP error 420 (420 status code 420) returned body: \"{\\\"code\\\":420,\\\"message\\\":null,\\\"cause\\\":\\\"\\\",\\\"error_id\\\":\\\"IncompleteUploadOpenApiException\\\",\\\"x-id\\\":\\\"092716313476\\\"}\"",
	"renames": 0,
	"retryError": true,
	"speed": 133936.3701245434,                                <--- This seems to be the value shown as average speed in the Global stats page. So here speed is average speed
	"transferring": [
		{
			"bytes": 127367552,
			"eta": 90,
			"group": "global_stats",
			"name": "Testordner/2016_12_22.mp4",
			"percentage": 74,
			"size": 170788658,
			"speed": 130416.75889405256,              <--- This seems to be the actual average speed of this job
			"speedAvg": 478355.4711809315           <--- This seems to be the actual (current) speed of this job
		}
	],
	"transfers": 1
}
`

**Comment by negative0** [comment]
Interesting. Thank you for bringing it to notice. @ncw what do you think?

**Comment by negative0** [comment]
If there is a problem with how rclone server is sending the data, we may have to move this issue to the rclone repository at github.com/rclone/rclone/issues.

**Comment by ncw** [comment]
> 			"speed": 130416.75889405256,            <--- This seems to be the actual average speed of this job
> 			"speedAvg": 478355.4711809315           <--- This seems to be the actual (current) speed of this job

`speed` here is total bytes / total time whereas `speedAvg` is an exponentially weighted average of the last few seconds of the data.

They probably aren't very well named but I think they have the data intended in.

    "speed": speed in bytes/sec - this is the average over the whole transfer
    "speedAvg": speed in bytes/sec as an exponentially weighted moving average - this is the average over the last few seconds

**Comment by JoshuaDietz** [comment]
@ncw 
> but I think they have the data intended in.

Unless I completely got it wrong it really doesn't look like that for me. To visualize it I started an upload and then after some time limited it to 100K (before the limit it was faster). Meanwhile I logged about every second answer of the stats calls. The JSON form is pretty long so you can find it [here](https://pastebin.com/iYsP15ss) if you need it but the short form below should probably be enough.

Each block is from one stats call. Elapsed time is from the root object just to give a feeling of the time here. The both other are from the job in the transferring section.

```
"elapsedTime": 140.126247474,
"speed": 619069.4824904844,
"speedAvg": 678979.9603240693

"elapsedTime": 145.128405775,
"speed": 622677.1877332567,
"speedAvg": 688592.9156572237


Now the change in the limit:
{
	"bytesPerSecond": 102400,
	"rate": "100k"
}

And it goes on like this now:

"elapsedTime": 150.424169153,
"speed": 622054.0887691305,
"speedAvg": 669034.6491311834

"elapsedTime": 155.382588255,
"speed": 603816.17792411,
"speedAvg": 513431.9914710703

"elapsedTime": 160.381392898,
"speed": 586869.2255509667,
"speedAvg": 398945.4934357397

"elapsedTime": 165.368063256,
"speed": 570865.8404381,
"speedAvg": 317616.55327818025

"elapsedTime": 170.37130261,
"speed": 556028.2029521259,
"speedAvg": 259056.5281359435

"elapsedTime": 175.367920628,
"speed": 541926.2443204098,
"speedAvg": 214726.5341603615

"elapsedTime": 180.367946173,
"speed": 528852.660124314,
"speedAvg": 184311.9866236121

"elapsedTime": 185.390179588,
"speed": 516471.8709569008,
"speedAvg": 162645.75560481776

"elapsedTime": 190.371787449,
"speed": 504723.6418280868,
"speedAvg": 144906.92824829134

"elapsedTime": 195.391177697,
"speed": 493695.6283281238,
"speedAvg": 133860.90620414764

"elapsedTime": 200.372662819,
"speed": 483356.8980371487,
"speedAvg": 124060.23922018468
```

So as you can see `speedAvg` drops pretty fast while `speed` almost stays the same/drops really slow. Why is that?

**Comment by ncw** [comment]
> So as you can see `speedAvg` drops pretty fast while `speed` almost stays the same/drops really slow. Why is that?

The speedAvg is the instantaneous speed and the speed is the long term average. So they should really be called speedShortTermAverage and speedLongTermAverage respectively.

**Comment by JoshuaDietz** [comment]
Okay I got it. So then in fact they are swapped in the webinterface. What do you think @negative0 ?

Also maybe this should be clarified in [https://rclone.org/rc/](https://rclone.org/rc/) in the core/stats section since `speed` it described as `speed in bytes/sec` which does not clarify that it's the average speed and also that `speedAvg` is the smoothed current speed. @ncw

**Comment by ncw** [comment]
> Also maybe this should be clarified in https://rclone.org/rc/ in the core/stats section since `speed` it described as `speed in bytes/sec` which does not clarify that it's the average speed and also that `speedAvg` is the smoothed current speed. @ncw

I fixed this in the docs - thank you for pointing out the confusion!

**Comment by negative0** [comment]
Thanks for pointing that out @JoshuaDietz .We could use the speedAvg for showing the transfer speed for jobs in progress. On it.
